"""
Phase 08 — Validation harness.

Reloads both trained artifacts from disk in a FRESH process (proving they
deserialize cleanly and require zero network calls), re-runs evaluation on
the held-out `val` split, and regenerates `ml/validation_report.md` with the
current numbers.

Run: cd ml && python validate.py
"""

import sys
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import (
    precision_score, recall_score, f1_score, roc_auc_score,
    average_precision_score, confusion_matrix,
)

from features import ML_FEATURES

DATA_PATH = Path(__file__).resolve().parent / "data" / "augmented.csv"
ART_DIR = Path(__file__).resolve().parent / "artifacts"
IFORST_PATH = ART_DIR / "isolation_forest.pkl"
XGB_PATH = ART_DIR / "xgboost_risk.pkl"
REPORT_PATH = Path(__file__).resolve().parent / "validation_report.md"


def _x_matrix(df, agent_types):
    X_feat = np.nan_to_num(df[ML_FEATURES].to_numpy(dtype=float), nan=0.0, posinf=0.0, neginf=0.0)
    onehot = np.zeros((len(df), len(agent_types)), dtype=float)
    type_idx = {t: i for i, t in enumerate(agent_types)}
    for i, t in enumerate(df["agent_type"].to_list()):
        if t in type_idx:
            onehot[i, type_idx[t]] = 1.0
    return np.hstack([X_feat, onehot]), df["is_agent_anomaly"].to_numpy(dtype=int).ravel()


def _iforest_flags(df, art, name_atype):
    flags = np.zeros(len(df), dtype=int)
    feats = lambda X: np.nan_to_num(X[ML_FEATURES].to_numpy(dtype=float), nan=0.0, posinf=0.0, neginf=0.0)
    for atype, sub in df.groupby(name_atype):
        m = art["models"].get(atype) or art["default"]
        if not m:
            continue
        Xs = m["scaler"].transform(feats(sub))
        flags[sub.index.to_numpy()] = (m["model"].predict(Xs) == -1).astype(int)
    return flags


def main() -> int:
    if not (IFORST_PATH.exists() and XGB_PATH.exists()):
        print(f"[err] artifacts missing — run train_isolation_forest.py and train_xgboost.py first.")
        return 1

    # Fresh-process load (proves deserialization + no network needed).
    with IFORST_PATH.open("rb") as f:
        iforest = pickle.load(f)
    with XGB_PATH.open("rb") as f:
        xgb_art = pickle.load(f)

    df = pd.read_csv(DATA_PATH)
    val = df[df["split"] == "val"].reset_index(drop=True)
    agent_types = xgb_art["agent_types"]

    # XGBoost
    Xv, yv = _x_matrix(val, agent_types)
    probs = xgb_art["model"].predict_proba(Xv)[:, 1]
    preds = (probs >= 0.5).astype(int)
    prec = precision_score(yv, preds, zero_division=0)
    rec = recall_score(yv, preds, zero_division=0)
    f1 = f1_score(yv, preds, zero_division=0)
    try:
        auc = roc_auc_score(yv, probs)
    except ValueError:
        auc = float("nan")
    auprc = average_precision_score(yv, probs)
    tn, fp, fn, tp = confusion_matrix(yv, preds, labels=[0, 1]).ravel()

    # Isolation Forest flag rate on val rogues vs normal
    val["agent_type"] = val["agent_type"].astype(str)
    iflags = _iforest_flags(val, iforest, "agent_type")
    if_pos = int(((iflags == 1) & (yv == 1)).sum())
    if_total_pos = int((yv == 1).sum())

    imps = xgb_art.get("feature_importances", [])
    top_lines = "\n".join(f"| `{n}` | {float(v):.4f} |" for n, v in imps[:12])
    TL = xgb_art.get("score_threshold_low", 0.30)
    TH = xgb_art.get("score_threshold_high", 0.70)

    report = f"""# ML Validation Report

Generated by `ml/validate.py` from a fresh-process reload of both artifacts.

## Model
- XGBoost + isotonic `CalibratedClassifierCV` (cv=3)
- Isolation Forest (per-agent-type, unsupervised)
- Target: `is_agent_anomaly`
- Features: behavioral set from `ml/features.py` ({len(ML_FEATURES)}) + agent_type one-hot ({len(agent_types)})

## Honest validation metrics (held-out `val` split — independent rogues)

| Metric | Value |
|---|---|
| Rows | {len(val)} |
| Positives | {int(yv.sum())} |
| XGBoost Precision | {prec:.4f} |
| XGBoost Recall | {rec:.4f} |
| XGBoost F1 | {f1:.4f} |
| XGBoost ROC-AUC | {auc:.4f} |
| XGBoost PR-AUC | {auprc:.4f} |

Confusion matrix (threshold 0.5): TP={tp} FP={fp} TN={tn} FN={fn}

## Isolation Forest (per-agent-type) flag rate on val rogues
- flagged {if_pos} / {if_total_pos} val rogues ({(if_pos/max(1,if_total_pos))*100:.1f}%)
(Independent signal; combined into the served `RiskScore.deny/escalate` band.)

## Serving decision bands (mirrored in backend config)
- score < {TL}  -> approve  (rules already passed)
- {TL} <= score < {TH} -> escalate  (human review queue)
- score >= {TH} -> deny

## Top feature importances (XGBoost gain)
| Feature | Importance |
|---|---|
{top_lines}

## Leakage fix verification
`ml/features.ML_FEATURES` contains no raw balance columns. See
`ml/data/augment_manifest.md` for the engineered-delta leakage fix.
All served features are derivable from the transaction stream + agent row
in-process (zero inference-time network calls).
"""
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"[ok] wrote report -> {REPORT_PATH}")
    print(f"     XGB: P={prec:.3f} R={rec:.3f} F1={f1:.3f} AUC={auc if auc==auc else 0:.3f} PR-AUC={auprc:.3f}")
    print(f"     IF  flagged {if_pos}/{if_total_pos} val rogues")
    return 0


if __name__ == "__main__":
    sys.exit(main())
